repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # antonbabenko/pre-commit-terraform@v1.98.0
    rev: e5f4170e017cfa2a848a1be0763bdab683076242
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
